# Generated by Django 4.2.3 on 2023-07-12 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.tickets.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('visibility', models.BooleanField(default=True)),
                ('status', models.PositiveSmallIntegerField(default=src.tickets.constants.TicketStatus['NOT_STARTED'])),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manager_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
