# Generated by Django 4.2.3 on 2023-07-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_category_ticket_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taken_at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='taken_at',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.taken_at'),
        ),
    ]
