# Generated by Django 4.2.3 on 2023-07-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_taken_at_ticket_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='taken_at',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='tickets.taken_at'),
        ),
    ]
