# Generated by Django 4.2.3 on 2023-07-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_taken_at_taken_at_alter_ticket_taken_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='taken_at',
        ),
        migrations.DeleteModel(
            name='Taken_at',
        ),
    ]
