name: action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner, formatter
    runs-on: ubuntu-latest
    env: 
#       CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts ("${{ env.CI_COMMIT_MESSAGE }}")
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Continuous Integration  
    steps:
      - uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: "."
      
      - uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          max-line-length: "120"

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Display event name 
        run: echo "github.event_name=${{ github.event_name }}"
      - name: Commit build artifacts (dist, devdist, docs, coverage)
        # Don't run again on already pushed auto commit. Don't run on pull request events.
        if: env.is-auto-commit == false && github.event_name != 'pull_request'
      - name: Change something
        run: |
          find . -type f -name "*.md" -print0 | xargs -0 sed -i "s/foo/bar/g"
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-COMMIT] foo/bar replace"
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Replaced foo/bar"
          title: ${{ github.event.commits[0].message }}



